### PR TITLE
Use SSH Control* options to multiplex connections

### PR DESCRIPTION
**Pull request by dberzano**
As opposed as opening one distinct SSH connection per alidock session

### CODE REVIEW

**Comment by dberzano** [comment]
Now, this works on Unix systems. Not sure about Windows (I don't know if the SSH client has the notion of "sockets", which are by the way not supported by the Windows filesystem). Let's test it first there.

**Comment by dberzano** [comment]
So, [ControlMaster is not supported in Windows OpenSSH](https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Scope). Have to add a condition.

**Comment by mconcas** [comment]
The WIP check miserably fails.
RIP

**Comment by dberzano** [comment]
It's not the WIP check... apparently Travis does not build draft PRs. That's a bummer.

**Comment by dberzano** [comment]
By using the SSH escape `~#` we can see what happens when we have four `alidock` terminals open:

```
[alidock] ~ $> ~#
The following connections are open:
  #1 mux-control (t16 r2 i0/0 o0/0 e[closed]/0 fd 8/8/-1 sock 8 cc -1)
  #2 client-session (t4 r0 i0/0 o0/0 e[write]/0 fd 9/10/11 sock -1 cc 1)
  #3 mux-control (t16 r4 i0/0 o0/0 e[closed]/0 fd 12/12/-1 sock 12 cc -1)
  #4 client-session (t4 r3 i0/0 o0/0 e[write]/0 fd 13/14/15 sock -1 cc 3)
  #5 mux-control (t16 r6 i0/0 o0/0 e[closed]/0 fd 16/16/-1 sock 16 cc -1)
  #6 client-session (t4 r6 i0/0 o0/0 e[write]/0 fd 17/18/19 sock -1 cc 5)
  #7 mux-control (t16 r8 i0/0 o0/0 e[closed]/0 fd 20/20/-1 sock 20 cc -1)
  #8 client-session (t4 r9 i0/0 o0/0 e[write]/4 fd 21/22/23 sock -1 cc 7)
```

We can see it's the same connection with several channels as expected.

**Review by mconcas — APPROVED** [review]

**Pull request merged**
