### PR TITLE
Use wheels and improve Travis CI output

### PR DESCRIPTION
**Pull request by dberzano**
* Produce wheels (PEP-491) instead of sdist tarballs for Python 2 and 3
* Always run `twine check`
* Deploy PRs to test repository

### CODE REVIEW

**Comment by dberzano** [comment]
@mconcas this is important in case we want to use wheels as in [PEP-491](https://www.python.org/dev/peps/pep-0491/). Test packages are deployed here for every pull request:

https://test.pypi.org/project/alidock/#history

Wheels are produced for Python 2 and 3, so we need to upload two `.whl` files (instead of a single sdist tarball).

Version number for development packages complies to [PEP-440](https://www.python.org/dev/peps/pep-0440/):

```
0.0.post<PR_NUM>.dev<TRAVIS_BUILD_NUM>
```

After the usual PyPI caching time (~15 minutes?), one can install the package with:

```bash
pip install --index-url https://test.pypi.org/simple/ "alidock==0.0.post<PR_NUM>.dev<TRAVIS_BUILD_NUM>"
```

Let's not merge this, but test it first.

**Comment by dberzano** [comment]
Oh by the way we should check in particular if `pip install` works with the standard Python version on CC7 and Ubuntu 14.04 (whose support ends in April this year).

**Comment by dberzano** [comment]
I have to amend the `pip` line:

```
pip install --extra-index-url https://test.pypi.org/simple/ "alidock==0.0.post<PR_NUM>.dev<TRAVIS_BUILD_NUM>"
```

It's `--extra-index-url` (not `--index-url`): this makes sure that `alidock` comes from the test repo, but all the dependencies come from upstream.

**Comment by dberzano** [comment]
And by the way, the binary wheel works on Ubuntu 14.04 LTS. SLC6 is never supported (has Python 2.6, we require 2.7).

**Review by mconcas — DISMISSED** [review]

**Comment by mconcas** [comment]
Ciao @dberzano, there were some conflicts, I possibly fixed them. Can you cross-check and proceed with merging?
Thanks

**Review by mconcas — APPROVED** [review]

**Pull request merged**
