### PR TITLE
Fix sshd params on older SSH

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
Better solutions are welcome...

**Review by mconcas — COMMENTED** [review]
Is it related to the distro or the `sshd` version?

**Comment by dberzano** [comment]
My point exactly. It's the `sshd` version. Now, that version does not even have `--help`. I don't know how to get the `sshd` version on slc6 😞

**Comment by dberzano** [comment]
(This is why this shouldn't be merged btw.)

**Comment by mconcas** [comment]
something like: 

`ssh -vN localhost | grep -i "remote protocol version"`?

Indeed, not so much cleaner than grepping "Centos 6" but at least it relies on the right parameter you want. 
Still, one should kill the command somehow, maybe with a timeout... :spaghetti:

**Comment by dberzano** [comment]
🍝 everywhere!

**Comment by dberzano** [comment]
@mconcas I like my  🍝 carbonara-style, I prefer leaving them out of my code. Better now?

**Review by mconcas — APPROVED** [review]

**Pull request merged**
