### PR TITLE
Improve feedback and help on user options

### LINKED ISSUE #112: Clarify what switches are not effective when container's already running
For instance: `--cvmfs` makes sense only when booting up the container. If one boots alidock without, and then enters a new shell with the switch, the switch is, at the moment, ineffective, and no message is printed. This is confusing.

### PR DESCRIPTION
**Pull request by dberzano**
* Wrapper class for handling options
* Warn if using opts only effective at alidock start
* Automatically generate config example

Fixes #112 and #73

### CODE REVIEW

**Comment by dberzano** [comment]
@mconcas this should do the trick however let's see if a) tests pass, and b) we come up in the next 18h with some more sensible warning message.

**Comment by dberzano** [comment]
Example:

```console
$> alidock --cvmfs --image asd
The following options are being ignored:
    --image
    --cvmfs
This is because alidock is already running and they are only valid when a new container is started.
You may want to stop alidock first with:
    alidock stop
and try again. Check `alidock --help` for more information
Starting a shell into the container
[alidock] ~ $>
```

**Comment by dberzano** [comment]
...and ready to be reviewed.

**Comment by dberzano** [comment]
Hold on, I may be able to solve #73 as well with a single PR.

**Comment by dberzano** [comment]
Perks of the new approach: automatically generate the help with `[configOptName]` appended, and automatically do the following at the end of the help:

```
it is possible to specify the most frequently used options in a YAML configuration file in /Users/volpe/.alidock-config.yaml
the following options (along with their default values) can be specified (please include `---` as first line):
---
dockName: alidock                  # same as option --name
updatePeriod: 43200                # same as option --update-period
dontUpdateAlidock: false           # same as option --no-update-alidock
debug: false                       # same as option --debug
imageName: alipier/alidock:latest  # same as option --image
dirOutside: ~/alidock              # same as option --shared
mount: []                          # same as option --mount
dontUpdateImage: false             # same as option --no-update-image
useNvidiaRuntime: false            # same as option --nvidia
enableRocmDevices: false           # same as option --rocm
cvmfs: false                       # same as option --cvmfs
web: false                         # same as option --web
```

**Review by mconcas — APPROVED** [review]
Clean AF

**Pull request merged**
