### PR TITLE
Enable optional X11 server in web browser

### LINKED ISSUE #110: Embed a web-based X11 server
Have something that gives the ability to use a web browser to access the container's X11. Useful for the following cases:

* Quick demonstrator: does not require X11 to be installed/running on the system to show results/bugs to new/occasional users. X11 requires extra packages on Windows and macOS.
* Because we can and it's cool to have everything embedded

The procedure was tested and it is incredibly simple.

* `alidock` should forward an additional port (other than `22/tcp`)
* `xpra` should be installed, [there's a repo file for CC7](https://xpra.org/repos/CentOS/xpra.repo)
* `xpra` should be [running](https://xpra.org/trac/wiki/Clients/HTML5)
* `DISPLAY` should be exported to `:0` in "web" mode, and SSH should not do X-forwarding

Installing `xpra` in the container is dead simple. Running it is simple as well:

```bash
xpra start --bind-tcp=0.0.0.0:14500 --html=on
```

It daemonizes automatically.

This is the result in the browser:

xpra

Ugly but effective.

The only relevant point of discussion is: how do we enable it? We have different options.

* `alidock --web`, but it must be the first alidock run. _All_ sessions will have `DISPLAY=:0`, and `ssh` will never do any X forwarding of any sort. We start `xpra` only in this case.
* We always start `xpra` at the container startup. X forwarding in SSH will be the normal way of using it, except when using `alidock --web`: in this case, alidock will:
  * Disable X forwarding
  * Export `DISPLAY=:0` _for the current session_
  * Immediately display the URL (including the randomly selected port) to use for displaying your X client in the browser

I'd go for the second option. Man this is so cool 😎

### PR DESCRIPTION
**Pull request by dberzano**
Use the `--web` switch to open a new alidock session where every X11 application
uses the embedded X11 server, exposing a TCP port where the display can be seen
through a web browser.

This method does not require any extra feature on the host node.

Fixes #110

### CODE REVIEW

**Comment by dberzano** [comment]
Note that this has a bug at the moment concerning how the `DISPLAY` variable is set.

**Comment by dberzano** [comment]
As agreed, what's left to do is:

- [x] Check what happens to fwd'd ports (are they bound to `0.0.0.0`?)
- [x] Start `alidock` either in normal X forwarding mode, or in web X mode

**Comment by dberzano** [comment]
Everything we've discussed has been implemented. Now `--web` must be passed when starting the container (it's ineffective otherwise). This is a problem but it will be solved for all switches in a separate PR, see #112.

Subsequent runs can simply use `alidock`. We check if the port is forwarded. If it is, we print a message saying how to access the X11 server from a web browser:

```console
$> alidock
Starting a shell into the container
X11 web browser access: http://localhost:32774
[alidock] ~ $>
```

**Review by mconcas — APPROVED** [review]
Well done, Let's wait for the Win compilation, for test. Then you can merge, I guess.

**Comment by dberzano** [comment]
winweb

**Comment by dberzano** [comment]
ALIDOCK IS SO META OMG
someta

**Pull request merged**
